[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn main:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[env]
PYTHON_VERSION = "3.9"
