[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python -m gunicorn main:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --log-level debug"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[env]
PYTHON_VERSION = "3.9"
FLASK_ENV = "production"
FLASK_DEBUG = "0"
PYTHONUNBUFFERED = "1"
